.empty_insertions <- function() GenomicRanges::GRanges()

.infer_tsd <- function(right_sequence, left_sequence) {
  if (!nzchar(right_sequence) || !nzchar(left_sequence)) {
    return("unknown")
  }
  right_sequence <- toupper(right_sequence)
  left_sequence <- toupper(left_sequence)
  for (width in seq.int(min(nchar(right_sequence), nchar(left_sequence)), 1L)) {
    overlap <- substr(right_sequence, 1L, width)
    if (identical(
      overlap,
      substr(left_sequence, nchar(left_sequence) - width + 1L, nchar(left_sequence))
    )) {
      return(overlap)
    }
  }
  "unknown"
}

#' Summarize short-read transposable element insertion evidence
#'
#' Reads the eight-column output from [insertLocation()], clusters nearby
#' breakpoints, and reports supporting reads on each side of an insertion.
#'
#' @param file Eight-column BED-like file generated by [insertLocation()].
#' @param max.gapwidth Maximum distance in bases used to combine nearby
#'   breakpoint evidence.
#'
#' @return A [GenomicRanges::GRanges()] object with transposable element name
#'   in both the legacy `name` field and the explicit `te_name` alias,
#'   target-site duplication, left and right support, total support, and mean
#'   assignment ratio.
#' @export
processInsertion <- function(file, max.gapwidth = 10L) {
  file <- .assert_input_file(file, "file")
  if (length(max.gapwidth) != 1L || !is.finite(max.gapwidth) || max.gapwidth < 0) {
    stop("max.gapwidth must be one non-negative integer", call. = FALSE)
  }
  if (file.size(file) == 0L) {
    return(.empty_insertions())
  }
  evidence <- utils::read.delim(
    file,
    header = FALSE,
    col.names = c(
      "seqname", "start0", "end0", "te_name", "sequence", "side",
      "support", "ratio"
    ),
    colClasses = c(
      "character", "integer", "integer", "character", "character",
      "integer", "numeric", "numeric"
    )
  )
  if (!nrow(evidence)) {
    return(.empty_insertions())
  }
  if (anyNA(evidence) || any(evidence$start0 < 0L) ||
      any(evidence$end0 <= evidence$start0) ||
      any(!evidence$side %in% c(1L, 2L)) || any(evidence$support <= 0) ||
      any(evidence$ratio < 0 | evidence$ratio > 1)) {
    stop("file contains invalid TEi breakpoint evidence", call. = FALSE)
  }

  ranges <- GenomicRanges::GRanges(
    seqnames = evidence$seqname,
    ranges = IRanges::IRanges(start = evidence$start0 + 1L, end = evidence$end0),
    te_name = evidence$te_name,
    sequence = evidence$sequence,
    side = evidence$side,
    support = evidence$support,
    ratio = evidence$ratio
  )
  clusters <- GenomicRanges::reduce(
    ranges,
    min.gapwidth = as.integer(max.gapwidth)
  )
  overlaps <- GenomicRanges::findOverlaps(clusters, ranges)
  members <- split(S4Vectors::subjectHits(overlaps), S4Vectors::queryHits(overlaps))

  summaries <- lapply(seq_along(clusters), function(i) {
    current <- ranges[members[[as.character(i)]]]
    support_by_te <- tapply(current$support, current$te_name, sum)
    te_name <- names(support_by_te)[which.max(support_by_te)]
    current <- current[current$te_name == te_name]
    right <- current[current$side == 1L]
    left <- current[current$side == 2L]
    left_support <- sum(left$support)
    right_support <- sum(right$support)
    tsd <- "unknown"
    if (length(left) && length(right)) {
      left_best <- left[which.max(left$support)]
      right_best <- right[which.max(right$support)]
      tsd <- .infer_tsd(right_best$sequence, left_best$sequence)
    }
    result <- clusters[i]
    result$name <- te_name
    result$te_name <- te_name
    result$tsd <- tsd
    result$left <- left_support
    result$right <- right_support
    result$support <- left_support + right_support
    result$mean_ratio <- stats::weighted.mean(current$ratio, current$support)
    result
  })
  do.call(c, summaries)
}
