.assert_input_file <- function(path, label) {
  if (!is.character(path) || length(path) != 1L || is.na(path) || !nzchar(path)) {
    stop(label, " must be one non-empty path", call. = FALSE)
  }
  if (!file.exists(path)) {
    stop(label, " does not exist: ", path, call. = FALSE)
  }
  normalizePath(path, mustWork = TRUE)
}

.prepare_output <- function(path, overwrite, label) {
  if (!is.character(path) || length(path) != 1L || is.na(path) || !nzchar(path)) {
    stop(label, " must be one non-empty path", call. = FALSE)
  }
  if (file.exists(path) && !isTRUE(overwrite)) {
    stop(label, " already exists: ", path, call. = FALSE)
  }
  if (file.exists(path)) {
    unlink(path)
  }
  path
}

.require_rbowtie2 <- function() {
  if (!requireNamespace("Rbowtie2", quietly = TRUE)) {
    stop(
      "Rbowtie2 is required for the short-read alignment step; install it with BiocManager::install('Rbowtie2').",
      call. = FALSE
    )
  }
}

#' Extract soft-clipped sequences
#'
#' Extracts terminal soft-clipped sequences from a host-genome SAM or BAM file
#' and writes them as FASTQ records. Breakpoint metadata are encoded in each
#' record name for the downstream short-read workflow.
#'
#' @param file Host-genome SAM or BAM file.
#' @param outfq Output FASTQ file.
#' @param mapq Minimum mapping quality.
#' @param length Minimum soft-clipped sequence length.
#' @param tsd Maximum target-site-duplication sequence length retained in the
#'   record name.
#' @param overwrite Replace an existing output file.
#'
#' @return The normalized output FASTQ path, invisibly.
#' @export
extractSoftClip <- function(file, outfq, mapq = 20L, length = 30L, tsd = 10L,
                            overwrite = FALSE) {
  file <- .assert_input_file(file, "file")
  outfq <- .prepare_output(outfq, overwrite, "outfq")
  values <- c(mapq = mapq, length = length, tsd = tsd)
  if (any(lengths(values) != 1L) || any(!is.finite(values)) ||
      mapq < 0 || length < 1 || tsd < 0) {
    stop("mapq, length, and tsd must be finite non-negative scalar values", call. = FALSE)
  }
  processbam(file, outfq, as.numeric(mapq), as.integer(length), as.integer(tsd))
  invisible(normalizePath(outfq, mustWork = TRUE))
}

#' Align clipped sequences to a transposable element reference
#'
#' @param reference Bowtie2 index prefix for the transposable element reference.
#' @param fastq FASTQ generated by [extractSoftClip()].
#' @param bamOutput Output BAM path or prefix.
#' @param threads Number of Bowtie2 threads.
#' @param overwrite Replace existing intermediate and output files.
#'
#' @return The query-name-sorted BAM path, invisibly.
#' @export
alignment <- function(reference, fastq, bamOutput, threads = 1L,
                      overwrite = FALSE) {
  .require_rbowtie2()
  fastq <- .assert_input_file(fastq, "fastq")
  if (!is.character(reference) || length(reference) != 1L || !nzchar(reference)) {
    stop("reference must be one Bowtie2 index prefix", call. = FALSE)
  }
  if (length(threads) != 1L || !is.finite(threads) || threads < 1) {
    stop("threads must be one positive integer", call. = FALSE)
  }

  prefix <- sub("\\.(sam|bam)$", "", bamOutput, ignore.case = TRUE)
  sam <- paste0(prefix, ".sam")
  bam <- paste0(prefix, ".bam")
  sorted_prefix <- paste0(prefix, ".sort")
  sorted_bam <- paste0(sorted_prefix, ".bam")
  for (path in c(sam, bam, sorted_bam)) {
    .prepare_output(path, overwrite, "alignment output")
  }

  Rbowtie2::bowtie2(
    bt2Index = reference,
    seq1 = fastq,
    samOutput = sam,
    commands = paste("--local --threads", as.integer(threads))
  )
  Rsamtools::asBam(sam, destination = prefix, overwrite = overwrite)
  Rsamtools::sortBam(
    file = bam,
    destination = sorted_prefix,
    byQname = TRUE,
    overwrite = overwrite
  )
  invisible(normalizePath(sorted_bam, mustWork = TRUE))
}

#' Convert transposable element alignments to breakpoint evidence
#'
#' @param file Query-name-sorted SAM or BAM generated by [alignment()].
#' @param outBed Output eight-column BED-like file.
#' @param ratio Minimum fraction of a clipped sequence's alignments assigned to
#'   one transposable element reference.
#' @param overwrite Replace an existing output file.
#'
#' @return The normalized output path, invisibly.
#' @export
insertLocation <- function(file, outBed, ratio = 0.1, overwrite = FALSE) {
  file <- .assert_input_file(file, "file")
  outBed <- .prepare_output(outBed, overwrite, "outBed")
  if (length(ratio) != 1L || !is.finite(ratio) || ratio < 0 || ratio > 1) {
    stop("ratio must be between zero and one", call. = FALSE)
  }
  processSam2bed(file, outBed, as.numeric(ratio))
  invisible(normalizePath(outBed, mustWork = TRUE))
}

#' Build a Bowtie2 transposable element index
#'
#' @param reference FASTA file containing transposable element sequences.
#' @param index Output index prefix.
#' @param overwrite Replace existing index files.
#' @param ... Additional arguments passed to `Rbowtie2::bowtie2_build()`.
#'
#' @return The value returned by `Rbowtie2::bowtie2_build()`.
#' @export
buildIndex <- function(reference, index, overwrite = FALSE, ...) {
  .require_rbowtie2()
  reference <- .assert_input_file(reference, "reference")
  Rbowtie2::bowtie2_build(
    references = reference,
    bt2Index = index,
    overwrite = overwrite,
    ...
  )
}
